### ISSUE TITLE
Look into collaborating with ampersand/magento2-upgrade-patch-helper

### ISSUE THREAD

**Issue by hostep** [sdinteractive/Magento2_SomethingDigital_UpgradeHelper#14]
Would it make sense to start a collaboration with https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/?
Since that tool is trying to solve the same thing you guys are trying to solve? And it might be more efficient if forces get combined?

**Comment by mpchadwick** [comment]
@hostep While we don't use it I've looked at the Ampersand tool in the past and it seems like a good option. Currently, SD has built some institutional knowledge around the use of our own in house tool and also have a set of diff files (which are a PITA to generate for Enterprise) that are compatible with the format processed by this tool. I think it's unlikely we'd join forces. The good thing is, you have multiple options and are free to use whichever tool you prefer :)
