### ISSUE TITLE
Upgrade Helper does not support layout xml files

### ISSUE THREAD

**Issue by swsavale** [sdinteractive/Magento2_SomethingDigital_UpgradeHelper#29]
Currently, Upgrade Helper runs through php, js, phtml, less extension files. It would be great if it can run through the layout xml files as well

**Comment by mpchadwick** [comment]
As layout XML isn't override based, but rather merge based, do you have thoughts on how we would do this?

**Comment by swsavale** [comment]
That's a good question. But nothing I know about this at the moment except matching file names?

**Comment by Leland** [comment]
We try not to override XML files at all - I don't know of any existing on our current portfolio. Closing - this is an issue admittedly but a minor one.
